### ISSUE TITLE
Add timeout to `Service Should Be Running` keyword

### ISSUE THREAD

**Issue by Bravo555** [reubenmiller/robotframework-devicelibrary#4]
I got the following exception using `Service Should Be Running` keyword:

```
[FAIL] `systemctl is-active tedge-mapp...` returned an unexpected exit code
stdout:
activating

stderr:

Traceback (most recent call last):
  file:///workspace/tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot#49 [Test if all c8y services using default service type when service type configured as empty]
    Test if all c8y services using default service type when service type configured as empty
  file:///workspace/tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot#51 (Check if a service using configured service type as empty)
    tedge-mapper-c8y
  file:///workspace/tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot#194 (Custom Test Setup)
    Custom Test Setup
  file:///workspace/tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot#133 (ThinEdgeIO.Service Should Be Running)
    ThinEdgeIO.Service Should Be Running    tedge-mapper-c8y
```

Instead of failing, the keyword should wait until the service starts up to some predetermined timeout, regularly retrying to see if service already started, e.g. every 1 second up to 5 seconds.

**Comment by Bravo555** [comment]
To provide more a bit context: this exception appeared when a service couldn't start because of an error that happened on startup, and systemd tried to restart it a whooping 30 times, which is the only reason why the service stayed in the `activating` state for as long as to even be detected here.

I fixed the problem with the service so it now starts successfully and doesn't restart, it's no longer a blocker for me.

**Comment by reubenmiller** [comment]
This is already supported. Keywords which support `**kwargs` should support the `timeout=<interval>` argument. The default timeout period is 30 seconds, so that's why you're seeing the 30seconds delay (and it retrying the assertion every second).
